name: Spotify

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3

      - uses: lowlighter/metrics@latest
        with:
          filename: spotify.svg
          token: ${{ secrets.GITHUB_TOKEN }}

          plugin_music: yes
          plugin_music_provider: spotify

          plugin_music_token: ${{ secrets.SPOTIFY_CLIENT_ID }}
          plugin_music_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          plugin_music_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
